.github/workflows/CI.yml, .gitignore, .gitmodules, Dockerfile, build.gradle
- CI 파이프라인 구축
- 서브모듈 연동
1. 서브모듈 관련 레포지토리 생성 및 메인 레포지토리와 연결
2. Github Actions & Docker 활용 CI 구축
1. .github/workflows/CI.yml 추가
2. config 관련 src/main/resources/application*.yml 추가
3.  Dockerfile 추가
> ### build.gradle
```java
// 서브모듈에서 설정 파일을 리소스 디렉토리로 복사하는 작업
tasks.register('copySecret', Copy) {
from 'config' // 서브 모듈 디렉토리 경로
include "*.yml"  // 설정 파일 복사
into 'src/main/resources/privates'  // 붙여넣을 위치
duplicatesStrategy = DuplicatesStrategy.INCLUDE // 중복 파일 처리 전략 설정
}
// `processResources` 작업이 `copySecret` 작업에 의존하도록 설정
tasks.named('processResources') {
duplicatesStrategy = DuplicatesStrategy.INCLUDE // 중복 파일 처리 전략 설정
dependsOn 'copySecret' // copySecret 작업이 먼저 실행되도록 설정
}
sourceSets {
main {
resources {
srcDirs "config"
}
}
}
```
> ### Dockerfile
```java
FROM openjdk:17-jdk-slim
WORKDIR /app …
```
=> 👷 [CI/#1] CI 파이프라인 구축

src/main/java/com/lckback/lckforall/mypage/dto/GetUserProfileDto.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
사용자 프로필 조회 API에 생략된 어노테이션 추가
1. GetUserProfileDto.Response : `@Getter` 추가
2. MyPageService : `@Transactional` 추가
resolved : #43
=> [Fix/#43]: add annotations 

src/main/java/com/lckback/lckforall/base/api/error/UserErrorCode.java, src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/dto/UpdateUserProfileDto.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java, src/main/java/com/lckback/lckforall/user/respository/UserRepository.java
사용자 프로필 업데이트 구현
1. UpdateUserProfileDto 추가
2. UserRepository : existsByNickname() 추가
3. UserErrorCode 추가
4. MyPageService, MyPageController : updateUserProfile() 구현
`/my-pages/profiles` URI에 `PATCH` method로 request
resolved : #33
=> [Feat/#33] update user's profile

src/main/java/com/lckback/lckforall/viewing/controller/ViewingChangeController.java, src/main/java/com/lckback/lckforall/viewing/controller/ViewingController.java, src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ParticipantListDTO.java, src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyService.java, src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyServiceImpl.java, src/test/java/com/lckback/lckforall/match/MatchServiceTest.java
뷰잉파티 참여자 리스트 조회
DTO만 따로 분리
https://www.notion.so/API-38e4db9c86b644a7b1b4bcf183551a84?p=843b49f2bce346f9b49028089479db9a&pm=s
=> [Feat/#62] get participant list

src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java, src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
기존 userId에서 accessToken -> kakaoUserId로 유저 식별
userId -> kakaoUserId
=> [Refactor/#81] apply jwt on my page

src/main/java/com/lckback/lckforall/vote/controller/VoteController.java, src/main/java/com/lckback/lckforall/vote/dto/MatchVoteDto.java, src/main/java/com/lckback/lckforall/vote/dto/SetVoteDto.java, src/main/java/com/lckback/lckforall/vote/service/VoteService.java
토큰 추가에 따른 로직 변경
VoteController, VoteService 내에 로그인 구현 가정하고 만든 코드를 로그인 로직이 구현됨에따라 변경
그에따라 변경된 dto파일 변경
=> [Refactor] 토큰 추가에 따른 로직 변경

src/main/java/com/lckback/lckforall/base/api/error/TokenErrorCode.java, src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
=> [Feat/#34] logout

build.gradle, src/main/java/com/lckback/lckforall/base/api/error/S3ErrorCode.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java, src/main/java/com/lckback/lckforall/base/config/S3Config.java, src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java, src/main/java/com/lckback/lckforall/s3/service/S3Service.java, src/main/java/com/lckback/lckforall/user/model/User.java
=> [Feat/#85] s3

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java, src/main/java/com/lckback/lckforall/user/converter/SignupUserDataConverter.java, src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java
=> [Refactor#80]: modify code related swagger

Dockerfile_release
=> [FEAT#70] Dockerfile_release dockerfile for release

.github/workflows/Deployment.yml
=> [Refactor] Deployment.yml

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java
=> Fix: modify swagger related signup

src/main/java/com/lckback/lckforall/base/config/WebConfiguration.java
cors를 위한  web configuration 추가
=> [Feat] add web configuration

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
/auth/refresh 관련 코드 수정
JWTFilter에 /auth/refresh 코드 추가, AuthService에 refresh에서 user 존재 먼저 판단하도록 코드 순서 변경
=> [Refactor#109] modify code related refresh path

.github/workflows/Deployment.yml
타겟 브랜치를 test 에서 release로 변경
release 브랜치에 배포 코드를 pr한 후 pr이 close되었을 때 배포 스크립트 실행
=> [CD#103] Deployment 깃허브 액션 타겟 브랜치 수정

src/main/java/com/lckback/lckforall/base/api/ApiResponse.java, src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
스웨거 활용을 휘한 return type 명시
MyPageController에서 return type 명시
ApiResponse의 createSuccessWithNoContent() 수정
변경된 로직 없음
resolved : #117
=> [Refactor/#117] my page : specify return type

src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
스웨거 활용을 위한 어노테이션 적용
`@SecurityRequirement`, `@SwaggerPageable` 추가
resolved : #120
=> [Refactor/#120]: apply `@SecurityRequirement`, `@SwaggerPageable`

src/main/java/com/lckback/lckforall/player/model/SeasonTeamPlayer.java
요구사항 변경에 따른 SeasonTeamPlayer 엔티티에 isCaptain 추가
=> [Refactor#122] add isCaptain field in SeasonTeamPlayer Entity

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
=> [Refactor/#114] modify auth swagger

src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
=> refactor : 뷰잉파티 엔티티 orphanRemoval 적용

src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java, src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java, src/main/java/com/lckback/lckforall/community/controller/CommentController.java, src/main/java/com/lckback/lckforall/community/controller/PostController.java, src/main/java/com/lckback/lckforall/community/dto/CommentDto.java, src/main/java/com/lckback/lckforall/community/dto/PostDto.java, src/main/java/com/lckback/lckforall/community/model/Post.java, src/main/java/com/lckback/lckforall/community/model/PostFile.java, src/main/java/com/lckback/lckforall/community/repository/PostFileRepository.java, src/main/java/com/lckback/lckforall/community/repository/PostRepository.java, src/main/java/com/lckback/lckforall/community/repository/PostTypeRepository.java, src/main/java/com/lckback/lckforall/community/service/CommentService.java, src/main/java/com/lckback/lckforall/community/service/PostService.java
커뮤니티 구현
화면설계서 community-7, community-8 구현 완료
제네릭 변경 완료 (ResponseEntity<?> 이부분에 타입 지정했습니다.
=> [Feat] community 구현 #41

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/base/auth/dto/GetNicknameDto.java, src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java, src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java, src/main/java/com/lckback/lckforall/user/model/User.java
프론트 요청에 따른 컬럼 추가, 닉네임 중복확인 api 추가
User 엔티티에 tier 컬럼 추가
회원가입 시 닉네임 중복 체크 api 추가
=> [Refactor/#129] add api to check duplicate nickname

src/main/java/com/lckback/lckforall/user/converter/SignupUserDataConverter.java, src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java, src/main/java/com/lckback/lckforall/user/model/User.java
유저 엔티티에 tier 컬럼 추가하면서 dto, converter 수정
=> [Refactor/#136] modify code related to user tier

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/base/auth/dto/GetNicknameDto.java, src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java, src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java, src/main/java/com/lckback/lckforall/match/controller/HomeController.java, src/main/java/com/lckback/lckforall/match/controller/MatchController.java, src/main/java/com/lckback/lckforall/match/controller/PogController.java, src/main/java/com/lckback/lckforall/match/dto/MatchInfoDto.java, src/main/java/com/lckback/lckforall/match/service/MatchService.java, src/main/java/com/lckback/lckforall/user/converter/SignupUserDataConverter.java, src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java, src/main/java/com/lckback/lckforall/user/model/User.java, src/main/java/com/lckback/lckforall/vote/controller/VoteController.java
=> release 0.0.1

src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ViewingPartyListDTO.java, src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
뷰잉파티 리스트 조회, 뷰잉파티 상세조회 주소정보 수정
- 뷰잉파티 리스트 : 부천시 역곡동
- 뷰잉파티 상세보기 : 부천시 역곡동 지봉로 24 @@카페
문자열 추출하는 메서드 적용
=> [refactor/#142] 뷰잉파티 리스트 조회, 뷰잉파티 상세조회 주소정보 수정

src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ViewingPartyListDTO.java, src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
=> release 0.0.2

src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java, src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ChangeViewingPartyDTO.java, src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
뷰잉파티 리스트에서 보일 짧은 주소 필드 추가
- Entity, DTO, Converter 단 수정
=> [refactor/#145] 뷰잉파티 리스트에서 보일 짧은 주소 필드 추가

src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ViewingPartyListDTO.java, src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
=> release 0.0.3

src/main/java/com/lckback/lckforall/base/api/error/CommentErrorCode.java, src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java, src/main/java/com/lckback/lckforall/report/controller/CommentReportController.java, src/main/java/com/lckback/lckforall/report/controller/PostReportController.java, src/main/java/com/lckback/lckforall/report/repository/CommentReportRepository.java, src/main/java/com/lckback/lckforall/report/repository/PostReportRepository.java, src/main/java/com/lckback/lckforall/report/service/CommentReportService.java, src/main/java/com/lckback/lckforall/report/service/PostReportService.java
커뮤니티 신고하기 api 구현
게시글 신고 api 구현
댓글 신고 api 구현
Post와 Comment 관련 ErrorCode 수정
중복 신고 검사 로직 추가
=> [Feat/#147] community add report api

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
요구사항에 맞게 dto 변경 (matchDate -> matchTime)
LocalDateTime 대신 LocalTime 사용하도록 변경
Match 검색할때 하루 전 매치까지 포함되는 부분 수정 -> 당일 매치만 검색되도록 시간 범위 수정
=> [Refactor/#150] aboutlck edit response date to time

src/main/java/com/lckback/lckforall/player/model/Player.java, src/main/java/com/lckback/lckforall/team/model/Team.java
url길이 설정 관련해서 엔티티 url 컬럼의 설정값 변경
=> [Refactor#152] : modify Entity for url length

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java, src/main/java/com/lckback/lckforall/base/api/error/CommentErrorCode.java, src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java, src/main/java/com/lckback/lckforall/player/model/Player.java, src/main/java/com/lckback/lckforall/report/controller/CommentReportController.java, src/main/java/com/lckback/lckforall/report/controller/PostReportController.java, src/main/java/com/lckback/lckforall/report/repository/CommentReportRepository.java, src/main/java/com/lckback/lckforall/report/repository/PostReportRepository.java, src/main/java/com/lckback/lckforall/report/service/CommentReportService.java, src/main/java/com/lckback/lckforall/report/service/PostReportService.java, src/main/java/com/lckback/lckforall/team/model/Team.java
=> releast 0.0.4

src/main/java/com/lckback/lckforall/match/service/MatchService.java
날짜 계산 로직 수정
어제 0시 ~ 오늘 24시
오늘 0시 ~ 오늘 24시
=> [Fix#156] fix today's match date logic

src/main/java/com/lckback/lckforall/match/controller/HomeController.java, src/main/java/com/lckback/lckforall/match/controller/MatchController.java, src/main/java/com/lckback/lckforall/match/controller/PogController.java, src/main/java/com/lckback/lckforall/vote/controller/VoteController.java
안드로이드쪽 요청 사항에 따른 swagger 관련 사항 수정
- @Operation 어노테이션 추가
=> [refactoring] swagger 관련 사항 수정

src/main/java/com/lckback/lckforall/match/controller/HomeController.java, src/main/java/com/lckback/lckforall/match/controller/MatchController.java, src/main/java/com/lckback/lckforall/match/controller/PogController.java, src/main/java/com/lckback/lckforall/match/service/MatchService.java, src/main/java/com/lckback/lckforall/vote/controller/VoteController.java
=> [refactoring] swagger 수정

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java, src/main/java/com/lckback/lckforall/viewing/controller/ViewingChangeController.java, src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java, src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ChangeViewingPartyDTO.java, src/main/java/com/lckback/lckforall/viewing/dto/GetViewingPartyDetailDTO.java, src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
create 로직에 맞춰서 shortLocation 수정 로직 구현
=> [refactor/#159] 뷰잉파티 리스트에서 보일 짧은 주소 update 로직 수정

src/main/java/com/lckback/lckforall/match/service/HomeService.java
home 화면 오류 수정
- home 화면 오늘의 매치 날짜 오류 수정
=> [fix] home화면 오류 수정

src/main/java/com/lckback/lckforall/match/service/HomeService.java
=> [fix] home화면 오류 수정 (#164)

src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
- auth controller 파라미터 어노테이션 수정
- 회원가입시 디폴트 이미지 설정 -> S3 주소
=> [Refactor/#159] auth update

src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java, src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
뷰잉파티 Request, Reponse DTO 포맷팅 로직 구현
DecimalFormat 적용
=> [Refactor/#170] 뷰잉파티 Request, Reponse DTO 포맷팅 로직 구현

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java
match detail dto에 matchdate 추가
=> [Refactor#173] : modify match detail dto field

src/main/java/com/lckback/lckforall/match/service/HomeService.java, src/main/java/com/lckback/lckforall/vote/dto/MatchVoteDto.java, src/main/java/com/lckback/lckforall/vote/repository/MatchVoteRepository.java, src/main/java/com/lckback/lckforall/vote/service/VoteService.java
match vote response에 투표 한 팀 id 추가
=> [Fix] match vote candidates response

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java, src/main/java/com/lckback/lckforall/vote/dto/MatchVoteDto.java, src/main/java/com/lckback/lckforall/vote/repository/MatchVoteRepository.java, src/main/java/com/lckback/lckforall/vote/service/VoteService.java
=> front 요청에 따른 home화면 response 값 수정

src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
안드 요청에 따라 네이밍 변경
request - > updateProfileRequest
=> [Refactor]: update form-data key name

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java, src/main/java/com/lckback/lckforall/vote/dto/MatchVoteDto.java, src/main/java/com/lckback/lckforall/vote/repository/MatchVoteRepository.java, src/main/java/com/lckback/lckforall/vote/service/VoteService.java
Reverts everyones-lck/lck-server#177
=> Revert "front 요청에 따른 home화면 response 값 수정"

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java, src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/vote/dto/MatchVoteDto.java, src/main/java/com/lckback/lckforall/vote/repository/MatchVoteRepository.java, src/main/java/com/lckback/lckforall/vote/service/VoteService.java
=> release 0.0.8

src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ParticipantListDTO.java, src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyServiceImpl.java
뷰잉파티 참여자 목록조회 Response DTO 필드 추가
=> [Refactor/#180] 뷰잉파티 참여자 목록조회 Response DTO 필드 추가

src/main/java/com/lckback/lckforall/viewing/converter/ChatConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ChatDTO.java, src/main/java/com/lckback/lckforall/viewing/service/ChatServiceImpl.java
1. 채팅기록 조회 API Response : isLast 변수, timeStamp 변수 추가
2. 채팅기록 조회 API Response : senderId -> senderName 변경
=> [refactor/#183] 채팅기록 조회 API Response 필드 추가

src/main/java/com/lckback/lckforall/base/api/error/CommentErrorCode.java, src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java, src/main/java/com/lckback/lckforall/community/controller/CommentController.java, src/main/java/com/lckback/lckforall/community/controller/PostController.java, src/main/java/com/lckback/lckforall/community/dto/CommentDto.java, src/main/java/com/lckback/lckforall/community/dto/PostDto.java, src/main/java/com/lckback/lckforall/community/model/Comment.java, src/main/java/com/lckback/lckforall/community/model/Post.java, src/main/java/com/lckback/lckforall/community/model/PostFile.java, src/main/java/com/lckback/lckforall/community/model/PostType.java, src/main/java/com/lckback/lckforall/community/repository/CommentRepository.java, src/main/java/com/lckback/lckforall/community/repository/PostFileRepository.java, src/main/java/com/lckback/lckforall/community/service/CommentService.java, src/main/java/com/lckback/lckforall/community/service/PostService.java
=> release 0.0.11

src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/dto/GetUserProfileDto.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
API 리팩토링
프로필 조회 시 팀 로고 이미지가 아닌 팀 아이디 반환
delete시 request body가 아닌 request param으로
=> [Refactor] : MyPage

src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/dto/GetUserProfileDto.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
=> release 0.0.12

src/main/java/com/lckback/lckforall/base/api/error/VoteErrorCode.java, src/main/java/com/lckback/lckforall/match/controller/MatchController.java, src/main/java/com/lckback/lckforall/match/dto/MatchInfoDto.java, src/main/java/com/lckback/lckforall/match/service/MatchService.java, src/main/java/com/lckback/lckforall/match/service/PogService.java
set count api 추가
프런트 요청 사항에 따른 예외 처리 수행
=> [Feat] 매치 별 set count api 추가 + 프런트 요청 사항에 따른 수정

src/main/java/com/lckback/lckforall/base/api/error/VoteErrorCode.java, src/main/java/com/lckback/lckforall/match/controller/MatchController.java, src/main/java/com/lckback/lckforall/match/dto/MatchInfoDto.java, src/main/java/com/lckback/lckforall/match/service/MatchService.java, src/main/java/com/lckback/lckforall/match/service/PogService.java
* feat: match의 set 수 반환 api 추가
- add set-count api
* fix: 프런트 요청 사항에 따른 수정
- 프런트 요청 사항에 따른 예외처리 수정
=> [Feat] 매치 별 set count api 추가 + 프런트 요청 사항에 따른 수정 (#190)

src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerInformationConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamPlayerInformationDto.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
dto에 isCaptain 필드 추가 요구사항 반영
1. converter 변경
2. dto 변경
3. service 변경
=> [Refactor/#192] about lck team modify dto to display captain

src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerInformationConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamPlayerInformationDto.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
=> release 0.0.14

src/main/java/com/lckback/lckforall/community/service/PostService.java
=> [Refactor#195] : modify postlist dto return value

src/main/java/com/lckback/lckforall/community/service/PostService.java
=> release 0.0.15

src/main/java/com/lckback/lckforall/community/service/PostService.java
=> refactor: CommentDto.CommentDetailDto getTeamName으로수정

src/main/java/com/lckback/lckforall/community/service/PostService.java
=> release 0.0.16

src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
=> [Refactor]: AboutLckMatchService

src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
=> release 0.0.17

src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
=> [Refactor#202] about lck team - modify converter logic

src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
=> release 0.0.18

src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
=> [Refactor#205] remove filter in converter

src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
=> release 0.0.19

src/main/java/com/lckback/lckforall/community/service/PostService.java
=> [Refactor]: return post sort by createdAt

src/main/java/com/lckback/lckforall/community/service/PostService.java
=> release 0.0.20

src/main/java/com/lckback/lckforall/base/type/PlayerRole.java
=> release 0.0.21

src/main/java/com/lckback/lckforall/community/dto/PostDto.java, src/main/java/com/lckback/lckforall/community/model/PostFile.java, src/main/java/com/lckback/lckforall/community/service/PostService.java, src/main/java/com/lckback/lckforall/s3/service/S3Service.java
=> [Refactor] return post file is image or video

src/main/java/com/lckback/lckforall/community/dto/PostDto.java, src/main/java/com/lckback/lckforall/community/model/PostFile.java, src/main/java/com/lckback/lckforall/community/service/PostService.java, src/main/java/com/lckback/lckforall/s3/service/S3Service.java
=> release 0.0.22

src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java, src/main/java/com/lckback/lckforall/viewing/dto/ParticipantListDTO.java
참여자 조회 API Response 카카오 유저 아이디 필드 추가
=> [refactor/#216] 참여자 조회 API Response 필드 추가

src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java, src/main/java/com/lckback/lckforall/user/model/User.java
계정 탈퇴시 데이터 삭제 처리
MyPageController : `@DeleteMapping` 사용
MyPageService : 실제로 데이터베이스에서 삭제
User : orphanRemoval 옵션 설정
=> [Refactor] withdrawal

src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java, src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java, src/main/java/com/lckback/lckforall/user/model/User.java
* Refactor(User): add orphanRemoval
* Refactor(MyPageService): delete data when with draw from account
* Refactor(MyPageController): use `@DeleteMapping`
=> release 0.0.24

src/main/java/com/lckback/lckforall/match/service/PogService.java, src/main/java/com/lckback/lckforall/vote/service/VoteService.java
데모데이때 시연을 위한 투표 제약 조건들 해제
- 투표가 종료되어야 결과가 나오던 제약 조건 해제 (주석처리)
- 투표기간이어야만 투표를 할 수 있던 제약 조건 해제 (주석처리)
=> [refactoring] drop vote constraint for demoday

src/main/java/com/lckback/lckforall/community/dto/PostDto.java, src/main/java/com/lckback/lckforall/community/service/PostService.java
PostDetail DTO 변경
그에 따른 PostService 변경
thumbnailFileUrl 추가
=> [Refactor#223] Modify DTO and postService logic

src/main/java/com/lckback/lckforall/base/auth/converter/AuthResponseConverter.java, src/main/java/com/lckback/lckforall/base/auth/dto/AuthResponseDto.java, src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
=> [refactor/#228] 로그인/회원가입시 사용자의 닉네임 반환

src/main/java/com/lckback/lckforall/community/dto/PostDto.java, src/main/java/com/lckback/lckforall/community/service/PostService.java
=> release 0.0.27

src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckPlayerService.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java, src/main/java/com/lckback/lckforall/team/repository/SeasonTeamRepository.java
=> release 0.0.28

src/main/java/com/lckback/lckforall/LckForAllApplication.java
=> [Refactor#233]  add @PostConstruct for modify timezone

src/main/java/com/lckback/lckforall/LckForAllApplication.java
=> release 0.0.29

src/main/java/com/lckback/lckforall/base/log/ApiLoggingAspect.java
스웨거 관련 오류 수정 - aop포인트컷 범위 지정
pointcut에 프로젝트 관련 패키지만 지정
=> [Fix/#250] edit pointcut scope to lck-for-all package

src/main/java/com/lckback/lckforall/base/log/ApiLoggingAspect.java
=> release 0.0.32

src/main/java/com/lckback/lckforall/community/dto/comment/CreateCommentDto.java, src/main/java/com/lckback/lckforall/community/dto/post/CreatePostDto.java, src/main/java/com/lckback/lckforall/community/dto/post/ModifyPostDto.java
=> [Fix#255] remove builder annotation in request dto

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
match 조회 dto 변경에 따른 로직 수정
match조회 범위를 기준 날짜 전날부터 다음날 까지로 정함
날짜에 따라 경기 정보를 구분하여 제공하도록 dto수정 및 converter 수정
=> [Refactor/#239] edit about lck match response

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
api 변경사항 작업
매치 없는 날 빈 리스트 리턴하도록 로직 변경
=> [Refactor#260] edit dto and converter to modify api response

src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java, src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
=> release 0.0.34
